import { useEffect, useState, type FormEvent } from 'react';
import { getChannels, getAdapters, getTemplates, saveChannel, saveAdapter, testChannel, newConfiguration, kindKeys, type Adapter, type Channel, type Template, type Configuration } from '../../api/channels';
import { safeFailure, type SafeError } from '../../api/client';
import { useI18n } from '../../i18n';
import { healthStatuses, labelKey } from '../../i18n/mappings';
import { Field, ErrorNotice } from '../../components/Forms';
import { ChannelHelp } from './ChannelHelp';
import { TestNotification } from './TestNotification';
import { useAuth } from '../auth/AuthContext';
function ConfigurationFields({ value, change }: { value: Configuration; change: (v: Configuration) => void }) {
  if (value.kind === 'TELEGRAM' || value.kind === 'MAX') return <Field id="channel-chat" labelKey="channels.chat" hint={value.kind === 'MAX' ? 'channels.maxChatHint' : 'channels.chatHint'}><input id="channel-chat" maxLength={21} value={value.chat_id} onChange={(e) => change({ ...value, chat_id: e.target.value })} /></Field>;
  if (value.kind === 'WEBHOOK') return <Field id="channel-url" labelKey="channels.url" hint="channels.urlHint"><input id="channel-url" type="url" maxLength={2000} value={value.url} onChange={(e) => change({ ...value, url: e.target.value })} /></Field>;
  return <MailFields value={value} change={change} />;
}
function MailFields({ value, change }: { value: Extract<Configuration, { kind: 'SMTP' }>; change: (v: Configuration) => void }) {
  const { t } = useI18n();
  return <>
    <div className="config-columns"><Field id="channel-host" labelKey="channels.host" hint="channels.hostHint"><input id="channel-host" maxLength={253} value={value.host} onChange={(e) => change({ ...value, host: e.target.value })} /></Field><Field id="channel-port" labelKey="channels.port" hint="channels.portHint"><input id="channel-port" type="number" min={1} max={65535} value={value.port} onChange={(e) => change({ ...value, port: Number(e.target.value) })} /></Field></div>
    <Field id="channel-tls" labelKey="channels.tls" hint="channels.tlsHint"><select id="channel-tls" value={value.tls} onChange={(e) => change({ ...value, tls: e.target.value as 'TLS' | 'STARTTLS' })}><option value="STARTTLS">{t('channels.starttls')}</option><option value="TLS">{t('channels.implicitTls')}</option></select></Field>
    <Field id="channel-username" labelKey="channels.username" hint="channels.usernameHint"><input id="channel-username" maxLength={320} autoComplete="off" value={value.username} onChange={(e) => change({ ...value, username: e.target.value })} /></Field>
    <Field id="channel-sender" labelKey="sources.sender" hint="channels.senderHint"><input id="channel-sender" type="email" maxLength={320} value={value.sender} onChange={(e) => change({ ...value, sender: e.target.value })} /></Field>
    <Field id="channel-recipients" labelKey="channels.recipients" hint="channels.recipientsHint"><textarea id="channel-recipients" rows={3} value={value.recipients.join('\n')} onChange={(e) => change({ ...value, recipients: e.target.value.split('\n') })} /></Field>
  </>;
}
export function ChannelsPage() {
  const { t, formatDate, formatNumber } = useI18n(); const auth = useAuth();
  const [testDraft, setTestDraft] = useState<Channel>();
  const [rows, setRows] = useState<Channel[]>(), [adapters, setAdapters] = useState<Adapter[]>([]), [templates, setTemplates] = useState<Template[]>([]), [draft, setDraft] = useState<Channel>(), [secret, setSecret] = useState(''), [clear, setClear] = useState(false);
  const [error, setError] = useState<SafeError>(), [busy, setBusy] = useState(false), [notice, setNotice] = useState<'saved' | 'CONNECTED' | 'TLS_ONLY' | 'BOT_VERIFIED'>(), [revision, setRevision] = useState(0);
  useEffect(() => { const c = new AbortController(); Promise.all([getChannels(c.signal), getAdapters(c.signal), getTemplates(c.signal)]).then(([r, a, ts]) => { if (!c.signal.aborted) { setRows(r.items); setAdapters(a.items); setTemplates(ts.items); } }).catch((e) => { if (!c.signal.aborted) setError(safeFailure(e)); }); return () => c.abort(); }, [revision]);
  const selectable = adapters.filter((a) => a.installed && a.enabled && a.visible);
  function edit(v: Channel) { setDraft(v); setSecret(''); setClear(false); setError(undefined); setNotice(undefined); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!draft || !auth.identity || busy) return; if (!draft.name.trim()) { setError({ key: 'channels.required' }); return; } setBusy(true); setError(undefined); setNotice(undefined); try { const saved = await saveChannel(draft, auth.identity.csrf_token, secret, clear); setRows((current) => current?.some((row) => row.id === saved.id) ? current.map((row) => row.id === saved.id ? saved : row) : [...(current ?? []), saved]); setSecret(''); setDraft(undefined); setNotice('saved'); setRevision((v) => v + 1); } catch (e) { setError(safeFailure(e)); } finally { setBusy(false); } }
  async function adapterSave(v: Adapter) { if (!auth.identity || busy) return; setBusy(true); setError(undefined); setNotice(undefined); try { await saveAdapter(v, auth.identity.csrf_token); setRevision((n) => n + 1); setNotice('saved'); } catch (e) { setError(safeFailure(e)); } finally { setBusy(false); } }
  async function probe(v: Channel) { if (!auth.identity || busy) return; setBusy(true); setError(undefined); setNotice(undefined); try { setNotice((await testChannel(v, auth.identity.csrf_token)).result); } catch (e) { setError(safeFailure(e)); } finally { setBusy(false); setRevision((n) => n + 1); } }
  return <>
    <div className="section-heading"><h1>{t('navigation.channels')}</h1><button disabled={busy || !selectable.length} onClick={() => { const kind = selectable[0].kind; edit({ id: '', name: '', kind, enabled: true, configured: false, available: false, version: 1, secret_version: 0, secret_configured: false, configuration: newConfiguration(kind), template_id: null, health_status: 'UNKNOWN', checked_at: null }); }}>{t('channels.create')}</button></div>
    <p className="muted">{t('channels.hint')}</p>{!draft && <ChannelHelp />}<ErrorNotice error={error} />{notice && <p role="status" className="notice">{t(({ saved: 'channels.saved', CONNECTED: 'channels.connected', TLS_ONLY: 'channels.tlsOnly', BOT_VERIFIED: 'channels.botVerified' } as const)[notice])}</p>}
    {testDraft && <TestNotification key={testDraft.id} channel={testDraft} close={() => setTestDraft(undefined)} />}
    {draft && <form noValidate className="card" onSubmit={(e) => void submit(e)}><h2>{t(draft.id ? 'channels.edit' : 'channels.create')}</h2><fieldset disabled={busy}>
      <Field id="channel-name" labelKey="config.name"><input id="channel-name" maxLength={120} value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></Field>
      <Field id="channel-kind" labelKey="channels.kind"><select id="channel-kind" value={draft.kind} disabled={Boolean(draft.id)} onChange={(e) => { const kind = e.target.value as Channel['kind']; setDraft({ ...draft, kind, configuration: newConfiguration(kind), template_id: null }); setSecret(''); setClear(false); }}>{(draft.id ? [draft.kind] : selectable.map((a) => a.kind)).map((k) => <option key={k} value={k}>{t(kindKeys[k])}</option>)}</select></Field>
      <ChannelHelp kind={draft.kind} />
      <ConfigurationFields value={draft.configuration} change={(configuration) => setDraft({ ...draft, configuration })} />
      <Field id="channel-secret" labelKey={draft.kind === 'SMTP' ? 'channels.password' : 'channels.token'} hint={draft.kind === 'SMTP' ? 'channels.smtpSecretHint' : draft.kind === 'WEBHOOK' ? 'channels.webhookSecretHint' : 'channels.botSecretHint'}><input id="channel-secret" type="password" autoComplete="new-password" maxLength={1024} disabled={clear} value={secret} onChange={(e) => setSecret(e.target.value)} /></Field>
      <p>{t(draft.secret_configured ? 'channels.secretConfigured' : 'channels.secretMissing')}</p>{draft.secret_configured && <label className="checkbox-field"><input type="checkbox" checked={clear} onChange={(e) => { setClear(e.target.checked); setSecret(''); }} />{t('channels.clearSecret')}</label>}
      {draft.secret_configured && <p className="field-hint">{t('channels.secretRevision', { version: formatNumber(draft.secret_version) })}</p>}
      {clear && <p className="notice warning">{t('channels.clearSecretHint')}</p>}
      {draft.id && <p className="field-hint">{t('channels.rotationHint')}</p>}
      <Field id="channel-template" labelKey="templates.single" hint="channels.templateHint"><select id="channel-template" value={draft.template_id ?? ''} onChange={(e) => setDraft({ ...draft, template_id: e.target.value || null })}><option value="">{t('channels.noTemplate')}</option>{templates.filter((v) => v.kind === draft.kind).map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>
      <label className="checkbox-field"><input type="checkbox" checked={draft.enabled} onChange={(e) => setDraft({ ...draft, enabled: e.target.checked })} />{t('channels.enabled')}</label>
      <div className="form-actions"><button type="submit">{t('common.save')}</button><button type="button" className="secondary" onClick={() => { setSecret(''); setDraft(undefined); setError(undefined); }}>{t('common.cancel')}</button></div>
    </fieldset></form>}
    {!rows && !error && <p role="status">{t('common.loading')}</p>}
    {rows && <section className="card table-scroll" tabIndex={0} role="region" aria-label={t('common.scrollTable')}>{!rows.length ? <p>{t('channels.empty')}</p> : <table><thead><tr><th>{t('config.name')}</th><th>{t('channels.kind')}</th><th>{t('users.status')}</th><th>{t('channels.connection')}</th><th>{t('users.actions')}</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.name}</td><td>{t(kindKeys[r.kind])}</td><td>{t(!r.enabled ? 'config.disabled' : r.available ? 'channels.ready' : 'channels.unavailable')}</td><td>{t(labelKey(healthStatuses, r.health_status))}{r.checked_at && <small>{formatDate(r.checked_at)}</small>}</td><td><div className="form-actions"><button className="secondary compact" disabled={busy} aria-label={t('config.editNamed', { name: r.name })} onClick={() => edit(r)}>{t('common.edit')}</button><button className="secondary compact" disabled={busy || !r.enabled} aria-label={t('channels.testNamed', { name: r.name })} onClick={() => void probe(r)}>{t('channels.test')}</button><button className="secondary compact" disabled={busy || !r.enabled || !r.configured} onClick={() => { setTestDraft(r); setDraft(undefined); setSecret(''); }}>{t('delivery.sendTest')}</button></div></td></tr>)}</tbody></table>}</section>}
    <section className="card"><h2>{t('channels.adapters')}</h2><p className="field-hint">{t('channels.adapterHint')}</p>{adapters.map((a) => <fieldset key={a.kind} disabled={busy}><legend>{t(kindKeys[a.kind])}</legend><p>{t(a.configured ? 'channels.networkConfigured' : 'channels.networkMissing')}</p><label className="checkbox-field"><input type="checkbox" checked={a.enabled} onChange={(e) => setAdapters(adapters.map((v) => v.kind === a.kind ? { ...v, enabled: e.target.checked } : v))} />{t('channels.adapterEnabled')}</label><label className="checkbox-field"><input type="checkbox" checked={a.visible} onChange={(e) => setAdapters(adapters.map((v) => v.kind === a.kind ? { ...v, visible: e.target.checked } : v))} />{t('channels.visible')}</label><p>{t('channels.pendingNotifications', { count: formatNumber(a.pending_notifications) })}</p>{a.affected_rules.length > 0 && <><p>{t('channels.affectedRules')}</p><ul>{a.affected_rules.map((name, i) => <li key={i}>{name}</li>)}</ul></>}<button className="secondary" onClick={() => void adapterSave(a)}>{t('channels.saveAdapter')}</button></fieldset>)}</section>
  </>;
}
