import { expect, test } from '@playwright/test';
import { authenticate } from './auth';
test.skip(!process.env.E2E_DIGEST_FIXTURE, 'Requires the isolated daily digest fixture');

test('viewer reads Russian digest totals, delivery and individual occurrences', async ({ page, baseURL }, info) => {
  await authenticate(page, baseURL!, 'viewer');
  await page.goto('/#digests');
  const row = page.getByRole('row').filter({ hasText: 'Ежедневная сводка межсетевого экрана' });
  await row.getByRole('button', { name: 'История запусков' }).click();
  await expect(page.getByText('Поступлений: 3. Отдельных событий: 1.', { exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Отправлено', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Состав сводки', exact: true }).click();
  await expect(page.getByRole('link', { name: 'digest-check Отклонено подключение' })).toHaveCount(3);
  await expect(page.getByRole('button', { name: 'Создать сводку' })).toHaveCount(0);
  await expect(page.locator('main')).not.toContainText(/WAITING|READY|DIGEST|Traceback/);
  await page.screenshot({ path: info.outputPath('digest-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 375, height: 812 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('digest-mobile.png'), fullPage: true });
});

test('administrator creates a daily digest and checks preview and versions without sending', async ({ page, baseURL }, info) => {
  await authenticate(page, baseURL!);
  await page.goto('/#digests');
  await page.getByRole('button', { name: 'Создать сводку', exact: true }).click();
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Не удалось сохранить сводку');
  const name = `Утренняя сводка ${Date.now()}`;
  await page.getByLabel('Название', { exact: true }).fill(name);
  await page.getByLabel('Канал уведомлений', { exact: true }).selectOption({ label: 'Локальная почта сводок' });
  await page.getByLabel('Шаблон сводки', { exact: true }).selectOption({ label: 'Почтовая сводка' });
  const time = page.getByLabel('Время отправки', { exact: true });
  await expect(time).toHaveAttribute('type', 'text');
  await expect(page.getByText('Введите время в формате ЧЧ:ММ, например 08:00 или 23:30.')).toBeVisible();
  await time.fill('24:00');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Не удалось сохранить сводку');
  await time.fill('08:00');
  await page.getByLabel('Межсетевой экран', { exact: true }).check();
  await page.getByLabel('Отбор поступлений', { exact: true }).selectOption('RULE');
  await page.setViewportSize({ width: 375, height: 812 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('digest-form-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Сводка сохранена');
  const row = page.getByRole('row').filter({ hasText: name });
  await row.getByRole('button', { name: 'Предпросмотр состава' }).click();
  await expect(page.getByText('Поступлений: 0. Отдельных событий: 0.', { exact: true })).toBeVisible();
  await row.getByRole('button', { name: 'Изменить', exact: true }).click();
  await page.getByLabel('Описание', { exact: true }).fill('Инструкция для дежурного');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Сводка сохранена');
  await row.getByRole('button', { name: 'История версий' }).click();
  await expect(page.getByText('Версия 2 · Администратор', { exact: false })).toBeVisible();
  await page.goto('/#routing');
  await page.getByRole('button', { name: 'Создать правило', exact: true }).click();
  await page.getByLabel('Название', { exact: true }).fill(name);
  await page.getByLabel('Действие', { exact: true }).selectOption('DIGEST');
  await page.getByLabel('Сводки', { exact: true }).selectOption({ label: name });
  await page.getByLabel('Значение', { exact: true }).fill('browser-digest-only');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Настройки сохранены');
});

test('only administrator can choose an explicitly incomplete digest', async ({ page, baseURL }) => {
  const identity = await authenticate(page, baseURL!, 'operator');
  await page.goto('/#digests');
  const row = page.getByRole('row').filter({ hasText: 'Сводка с задержкой обработки' });
  await row.getByRole('button', { name: 'История запусков' }).click();
  await expect(page.getByText('Требуется решение', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Отправить неполную сводку', exact: true })).toHaveCount(0);
  const list = await (await page.request.get('/api/v1/digests')).json();
  const id = list.items.find((v: { name: string }) => v.name === 'Сводка с задержкой обработки').id;
  const runs = await (await page.request.get(`/api/v1/digests/${id}/runs`)).json();
  const denied = await page.request.post(`/api/v1/digests/runs/${runs.items[0].id}/partial`, { headers: { Origin: new URL(baseURL!).origin, 'X-CSRF-Token': identity.csrf_token }, data: { version: runs.items[0].version, operation_key: crypto.randomUUID() } });
  expect(denied.status()).toBe(403);
  await authenticate(page, baseURL!);
  await page.reload();
  await row.getByRole('button', { name: 'История запусков' }).click();
  await page.getByRole('button', { name: 'Отправить неполную сводку', exact: true }).click();
  await expect(page.getByRole('alertdialog')).toContainText('Остальные не войдут в отправку');
  await page.getByRole('alertdialog').getByRole('button', { name: 'Отправить неполную сводку', exact: true }).click();
  await expect(page.getByText('Неполная сводка', { exact: true })).toBeVisible();
  await expect(page.getByText('На момент подготовки не обработано: 1.', { exact: true })).toBeVisible();
});
