import { ApiError, requestJson } from './client';
import { record, string, integer, bool, page } from './configuration';
import type { TranslationKey } from '../i18n';
export const kinds = ['SMTP', 'TELEGRAM', 'MAX', 'WEBHOOK'] as const;
export type Kind = typeof kinds[number];
export const kindKeys = { SMTP: 'channels.kind.SMTP', TELEGRAM: 'channels.kind.TELEGRAM', MAX: 'channels.kind.MAX', WEBHOOK: 'channels.kind.WEBHOOK' } satisfies Record<Kind, TranslationKey>;
export type Configuration = { kind: 'SMTP'; host: string; port: number; tls: 'TLS' | 'STARTTLS'; username: string; sender: string; recipients: string[] } | { kind: 'TELEGRAM'; chat_id: string } | { kind: 'MAX'; chat_id: string } | { kind: 'WEBHOOK'; url: string };
export interface Adapter { kind: Kind; installed: boolean; enabled: boolean; visible: boolean; configured: boolean; health_status: string; version: number; affected_rules: string[]; pending_notifications: number }
export interface Channel { id: string; name: string; kind: Kind; enabled: boolean; configured: boolean; available: boolean; version: number; secret_version: number; secret_configured: boolean; configuration: Configuration; template_id: string | null; health_status: string; checked_at: string | null }
export interface Template { id: string; name: string; kind: Kind; version: number; subject: string; body: string; html: string }
export interface Preview { subject: string; body: string; html: string; payload: string }
export interface TemplateVersion { version: number; author: string; created_at: string; snapshot: Template }
const bad = () => new ApiError({ key: 'errors.internalWithoutId' });
function kind(v: unknown): Kind { if (!kinds.includes(v as Kind)) throw bad(); return v as Kind; }
function date(v: unknown) { const s = string(v, 40); if (!Number.isFinite(Date.parse(s))) throw bad(); return s; }
function id(v: unknown) { const s = string(v, 36); if (!/^[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12}$/.test(s)) throw bad(); return s; }
export function parseAdapter(value: unknown): Adapter { const v = record(value); if (!Array.isArray(v.affected_rules) || v.affected_rules.length > 100) throw bad(); return { kind: kind(v.kind), installed: bool(v.installed), enabled: bool(v.enabled), visible: bool(v.visible), configured: bool(v.configured), health_status: string(v.health_status, 16), version: integer(v.version), affected_rules: v.affected_rules.map((s) => string(s, 120)), pending_notifications: integer(v.pending_notifications ?? 0) }; }
export function parseConfiguration(value: unknown): Configuration { const v = record(value), k = kind(v.kind); if (k === 'TELEGRAM' || k === 'MAX') return { kind: k, chat_id: string(v.chat_id, 21) }; if (k === 'WEBHOOK') return { kind: k, url: string(v.url) }; if (!['TLS', 'STARTTLS'].includes(String(v.tls)) || !Array.isArray(v.recipients) || v.recipients.length > 20) throw bad(); return { kind: k, host: string(v.host, 253), port: integer(v.port), tls: v.tls as 'TLS' | 'STARTTLS', username: string(v.username, 320), sender: string(v.sender, 320), recipients: v.recipients.map((s) => string(s, 320)) }; }
export function parseChannel(value: unknown): Channel { const v = record(value), configuration = parseConfiguration(v.configuration); if (kind(v.kind) !== configuration.kind) throw bad(); return { id: id(v.id), name: string(v.name, 120), kind: configuration.kind, enabled: bool(v.enabled), configured: bool(v.configured), available: bool(v.available), version: integer(v.version), secret_version: integer(v.secret_version), secret_configured: bool(v.secret_configured), configuration, template_id: v.template_id === null ? null : id(v.template_id), health_status: string(v.health_status, 16), checked_at: v.checked_at === null ? null : date(v.checked_at) }; }
export function parseTemplate(value: unknown): Template { const v = record(value); return { id: v.id == null ? '' : id(v.id), name: string(v.name, 120), kind: kind(v.kind), version: integer(v.version), subject: string(v.subject), body: string(v.body, 16384), html: string(v.html, 16384) }; }
export function parsePreview(value: unknown): Preview { const v = record(value); return { subject: string(v.subject, 998), body: string(v.body, 65536), html: string(v.html, 65536), payload: string(v.payload, 65536) }; }
export function newConfiguration(k: Kind): Configuration { return k === 'SMTP' ? { kind: k, host: '', port: 587, tls: 'STARTTLS', username: '', sender: '', recipients: [''] } : (k === 'TELEGRAM' || k === 'MAX') ? { kind: k, chat_id: '' } : { kind: k, url: '' }; }
export async function getChannels(signal?: AbortSignal) { return page(await requestJson('/api/v1/channels', { signal }), parseChannel); }
export async function getAdapters(signal?: AbortSignal) { return page(await requestJson('/api/v1/output-adapters', { signal }), parseAdapter); }
export async function saveAdapter(v: Adapter, csrf: string) { return parseAdapter(await requestJson(`/api/v1/output-adapters/${v.kind}`, { method: 'PATCH', csrf, body: { version: v.version, enabled: v.enabled, visible: v.visible } })); }
export async function saveChannel(v: Channel, csrf: string, secret: string, clear_secret: boolean) { const body = { name: v.name, enabled: v.enabled, version: v.version, secret_version: v.secret_version, template_id: v.template_id, configuration: v.configuration, ...(secret ? { secret } : {}), clear_secret }; return parseChannel(await requestJson(`/api/v1/channels${v.id ? `/${v.id}` : ''}`, { method: v.id ? 'PATCH' : 'POST', csrf, body })); }
export async function testChannel(v: Channel, csrf: string) { const r = record(await requestJson(`/api/v1/channels/${v.id}/test-connection`, { method: 'POST', csrf })); if (!['CONNECTED', 'TLS_ONLY', 'BOT_VERIFIED'].includes(String(r.result))) throw bad(); return { result: r.result as 'CONNECTED' | 'TLS_ONLY' | 'BOT_VERIFIED', channel: parseChannel(r.channel) }; }
export async function getTemplates(signal?: AbortSignal) { return page(await requestJson('/api/v1/templates', { signal }), parseTemplate); }
export async function saveTemplate(v: Template, csrf: string) { const { id, ...body } = v; return parseTemplate(await requestJson(`/api/v1/templates${id ? `/${id}` : ''}`, { method: id ? 'PATCH' : 'POST', body, csrf })); }
export async function previewTemplate(v: Template, event: Record<string, string>, csrf: string) { const { id: _, ...template } = v; return parsePreview(await requestJson('/api/v1/templates/preview', { method: 'POST', csrf, body: { template, event } })); }
export async function getTemplateVersions(identifier: string, offset: number, signal?: AbortSignal) { return page(await requestJson(`/api/v1/templates/${identifier}/versions?offset=${offset}`, { signal }), (v): TemplateVersion => { const r = record(v); return { version: integer(r.version), author: string(r.author, 120), created_at: date(r.created_at), snapshot: parseTemplate(r.snapshot) }; }); }
