import { ApiError, requestJson } from './client';
import { bool, integer, page, record, string } from './configuration';
import { DigestStateValues, DigestPeriodValues, DigestSelectionValues, SeverityValues, NotificationStatusValues, type DigestState, type DigestPeriod, type DigestSelection, type Severity, type NotificationStatus } from './generated';
import type { Operation } from './notifications';
export interface Digest { id: string; name: string; description: string; enabled: boolean; version: number; channel_id: string; template_id: string; time_zone: string; minute_of_day: number; period: DigestPeriod; selection: DigestSelection; source_ids: string[]; severities: (Severity | '')[]; wait_seconds: number; send_empty: boolean; created_at?: string; window_start?: string; next_end?: string }
export interface Item { event_id: string; subject: string; received_at: string }
export interface Summary { occurrences: number; events: number; first: string | null; last: string | null; sources: { label: string; count: number }[]; severities: { label: Severity | ''; count: number }[]; frequent: { event_id: string; subject: string; count: number }[] }
export interface Run { id: string; name: string; definition_version: number; version: number; state: DigestState; window_start: string; window_end: string; review_at: string; partial: boolean; pending_count: number; missing_at_cutoff: number; late_count: number; summary: Summary | null; notification_id: string | null; notification_status: NotificationStatus | null }
export interface Preview { window_start: string; window_end: string; occurrences: number; events: number; pending_count: number; items: Item[] }
const bad = () => new ApiError({ key: 'errors.internalWithoutId' });
function id(v: unknown) { const s = string(v, 36); if (!/^[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12}$/.test(s)) throw bad(); return s; }
function date(v: unknown) { const s = string(v, 40); if (!Number.isFinite(Date.parse(s))) throw bad(); return s; }
function list<T>(v: unknown, parse: (x: unknown) => T, max: number): T[] { if (!Array.isArray(v) || v.length > max) throw bad(); return v.map(parse); }
function enumeration<T extends string>(v: unknown, values: readonly T[]): T { if (typeof v !== 'string' || !values.includes(v as T)) throw bad(); return v as T; }
export function parseDigest(value: unknown): Digest { const v = record(value); const minute = integer(v.minute_of_day), wait = integer(v.wait_seconds); if (minute > 1439 || wait < 60 || wait > 604800) throw bad(); return { id: v.id == null ? '' : id(v.id), name: string(v.name, 120), description: string(v.description, 2000), enabled: bool(v.enabled), version: integer(v.version), channel_id: id(v.channel_id), template_id: id(v.template_id), time_zone: string(v.time_zone, 80), minute_of_day: minute, period: enumeration(v.period, DigestPeriodValues), selection: enumeration(v.selection, DigestSelectionValues), source_ids: list(v.source_ids, id, 100), severities: list(v.severities, (s) => enumeration(s, ['', ...SeverityValues] as const), 6), wait_seconds: wait, send_empty: bool(v.send_empty), ...(v.created_at == null ? {} : { created_at: date(v.created_at), window_start: date(v.window_start), next_end: date(v.next_end) }) }; }
export function parseSummary(value: unknown): Summary | null { const v = record(value); if (Object.keys(v).length === 0) return null; const group = (g: unknown) => { const r = record(g); return { label: string(r.label, 120), count: integer(r.count) }; }; return { occurrences: integer(v.occurrences), events: integer(v.events), first: v.first === null ? null : date(v.first), last: v.last === null ? null : date(v.last), sources: list(v.sources, group, 20), severities: list(v.severities, (g) => { const r = group(g); return { ...r, label: enumeration(r.label, ['', ...SeverityValues] as const) }; }, 6), frequent: list(v.frequent, (g) => { const r = record(g); return { event_id: id(r.event_id), subject: string(r.subject, 500), count: integer(r.count) }; }, 20) }; }
export function parseRun(value: unknown): Run { const v = record(value); return { id: id(v.id), name: string(v.name, 120), definition_version: integer(v.definition_version), version: integer(v.version), state: enumeration(v.state, DigestStateValues), window_start: date(v.window_start), window_end: date(v.window_end), review_at: date(v.review_at), partial: bool(v.partial), pending_count: integer(v.pending_count), missing_at_cutoff: integer(v.missing_at_cutoff), late_count: integer(v.late_count), summary: parseSummary(v.summary), notification_id: v.notification_id === null ? null : id(v.notification_id), notification_status: v.notification_status === null ? null : enumeration(v.notification_status, NotificationStatusValues) }; }
export function parseItem(value: unknown): Item { const v = record(value); return { event_id: id(v.event_id), subject: string(v.subject, 500), received_at: date(v.received_at) }; }
export async function getDigests(signal?: AbortSignal) { return page(await requestJson('/api/v1/digests', { signal }), parseDigest); }
export async function saveDigest(v: Digest, csrf: string) { const { id, created_at: _, window_start: __, next_end: ___, ...body } = v; return parseDigest(await requestJson('/api/v1/digests' + (id ? `/${id}` : ''), { method: id ? 'PATCH' : 'POST', body, csrf })); }
export async function getRuns(id: string, offset: number, signal?: AbortSignal) { return page(await requestJson(`/api/v1/digests/${id}/runs?offset=${offset}`, { signal }), parseRun); }
export async function getItems(id: string, late: boolean, offset: number, signal?: AbortSignal) { return page(await requestJson(`/api/v1/digests/runs/${id}/items?late=${late}&offset=${offset}`, { signal }), parseItem); }
export async function getVersions(id: string, offset: number, signal?: AbortSignal) { return page(await requestJson(`/api/v1/digests/${id}/versions?offset=${offset}`, { signal }), (v) => { const r = record(v); return { version: integer(r.version), author: string(r.author, 120), created_at: date(r.created_at), snapshot: parseDigest(r.snapshot) }; }); }
export async function getPreview(id: string, signal?: AbortSignal): Promise<Preview> { const v = record(await requestJson(`/api/v1/digests/${id}/preview`, { signal })); return { window_start: date(v.window_start), window_end: date(v.window_end), occurrences: integer(v.occurrences), events: integer(v.events), pending_count: integer(v.pending_count), items: list(v.items, parseItem, 25) }; }
export async function decide(id: string, action: 'wait' | 'partial', body: Operation, csrf: string) { return parseRun(await requestJson(`/api/v1/digests/runs/${id}/${action}`, { method: 'POST', body, csrf })); }
export function newDigest(): Digest { return { id: '', name: '', description: '', enabled: true, version: 1, channel_id: '', template_id: '', time_zone: 'Europe/Moscow', minute_of_day: 480, period: 'CALENDAR', selection: 'FILTER', source_ids: [], severities: [], wait_seconds: 3600, send_empty: false }; }
