import { ApiError, requestJson } from './client';
import { bool, integer, page, record, string } from './configuration';
import { EventStatusValues, EscalationStateValues, EscalationStepStateValues, NotificationStatusValues, type EventStatus, type EscalationState, type EscalationStepState, type NotificationStatus } from './generated';
import type { Operation } from './notifications';
export interface Step { channel_id: string; delay_seconds: number }
export interface Policy { id: string; name: string; description: string; enabled: boolean; version: number; steps: Step[] }
export interface Version { version: number; author: string; created_at: string; snapshot: Policy }
export interface EventState { version: number; status: EventStatus; acknowledged_by: string | null; acknowledged_at: string | null }
export interface EventAction { id: string; author: string; from_status: EventStatus; to_status: EventStatus; created_at: string }
export type Action = 'acknowledge' | 'resolve' | 'suppress';
export interface Run { id: string; name: string; version: number; state: EscalationState; created_at: string; stopped_at: string | null; stop_reason: EventStatus | null; steps: { ordinal: number; due_at: string; state: EscalationStepState; channel_name: string; notification_id: string | null; notification_status: NotificationStatus | null }[] }
const bad = () => new ApiError({ key: 'errors.internalWithoutId' });
function id(v: unknown) { const s = string(v, 36); if (!/^[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12}$/.test(s)) throw bad(); return s; }
function date(v: unknown) { const s = string(v, 40); if (!Number.isFinite(Date.parse(s))) throw bad(); return s; }
function enumeration<T extends string>(v: unknown, values: readonly T[]): T { if (typeof v !== 'string' || !values.includes(v as T)) throw bad(); return v as T; }
export function parsePolicy(value: unknown): Policy { const v = record(value); if (!Array.isArray(v.steps) || !v.steps.length || v.steps.length > 10) throw bad(); return { id: v.id == null ? '' : id(v.id), name: string(v.name, 120), description: string(v.description, 2000), enabled: bool(v.enabled), version: integer(v.version), steps: v.steps.map((s) => { const step = record(s); const delay = integer(step.delay_seconds); if (delay > 2592000) throw bad(); return { channel_id: id(step.channel_id), delay_seconds: delay }; }) }; }
export function parseState(value: unknown): EventState { const v = record(value); return { version: integer(v.version), status: enumeration(v.status, EventStatusValues), acknowledged_by: v.acknowledged_by === null ? null : string(v.acknowledged_by, 120), acknowledged_at: v.acknowledged_at === null ? null : date(v.acknowledged_at) }; }
export function parseEventAction(value: unknown): EventAction { const v = record(value); return { id: id(v.id), author: string(v.author, 120), from_status: enumeration(v.from_status, EventStatusValues), to_status: enumeration(v.to_status, EventStatusValues), created_at: date(v.created_at) }; }
export function parseRun(value: unknown): Run { const v = record(value); if (!Array.isArray(v.steps) || v.steps.length > 10) throw bad(); return { id: id(v.id), name: string(v.name, 120), version: integer(v.version), state: enumeration(v.state, EscalationStateValues), created_at: date(v.created_at), stopped_at: v.stopped_at === null ? null : date(v.stopped_at), stop_reason: v.stop_reason === null ? null : enumeration(v.stop_reason, EventStatusValues), steps: v.steps.map((value) => { const s = record(value); return { ordinal: integer(s.ordinal), due_at: date(s.due_at), state: enumeration(s.state, EscalationStepStateValues), channel_name: string(s.channel_name, 120), notification_id: s.notification_id === null ? null : id(s.notification_id), notification_status: s.notification_status === null ? null : enumeration(s.notification_status, NotificationStatusValues) }; }) }; }
export async function getPolicies(signal?: AbortSignal) { return page(await requestJson('/api/v1/escalation-policies', { signal }), parsePolicy); }
export async function savePolicy(value: Policy, csrf: string) { const { id, ...body } = value; return parsePolicy(await requestJson('/api/v1/escalation-policies' + (id ? `/${id}` : ''), { method: id ? 'PATCH' : 'POST', body, csrf })); }
export async function getVersions(id: string, offset: number, signal?: AbortSignal) { return page(await requestJson(`/api/v1/escalation-policies/${id}/versions?offset=${offset}`, { signal }), (value): Version => { const v = record(value); return { version: integer(v.version), author: string(v.author, 120), created_at: date(v.created_at), snapshot: parsePolicy(v.snapshot) }; }); }
export async function getRuns(id: string, offset: number, signal?: AbortSignal) { return page(await requestJson(`/api/v1/events/${id}/escalations?offset=${offset}`, { signal }), parseRun); }
export async function getActions(id: string, offset: number, signal?: AbortSignal) { const value = await requestJson(`/api/v1/events/${id}/actions?offset=${offset}`, { signal }); return { ...parseState(value), ...page(value, parseEventAction) }; }
export async function changeEvent(id: string, action: Action, body: Operation, csrf: string) { return parseState(await requestJson(`/api/v1/events/${id}/actions/${action}`, { method: 'POST', body, csrf })); }
