// Generated by scripts/generate-api-types.py. Do not edit manually.

export const RuleActionValues = ['SET_FIELDS', 'SUPPRESS', 'NOTIFY', 'DIGEST', 'ESCALATE'] as const;
export type RuleAction = typeof RuleActionValues[number];

export const ActionOutcomeValues = ['APPLIED', 'PLANNED', 'SUPPRESSED', 'REPEAT', 'OVERRIDDEN'] as const;
export type ActionOutcome = typeof ActionOutcomeValues[number];

export const EventStatusValues = ['NEW', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED'] as const;
export type EventStatus = typeof EventStatusValues[number];

export const EscalationStateValues = ['ACTIVE', 'COMPLETED', 'STOPPED'] as const;
export type EscalationState = typeof EscalationStateValues[number];

export const EscalationStepStateValues = ['WAITING', 'QUEUED', 'CANCELLED'] as const;
export type EscalationStepState = typeof EscalationStepStateValues[number];

export const NotificationStatusValues = ['PENDING', 'PROCESSING', 'SENT', 'FAILED', 'RETRYING', 'CANCELLED'] as const;
export type NotificationStatus = typeof NotificationStatusValues[number];

export const SeverityValues = ['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'] as const;
export type Severity = typeof SeverityValues[number];

export const DeliveryModeValues = ['IMMEDIATE', 'DELAYED', 'SCHEDULED', 'DIGEST'] as const;
export type DeliveryMode = typeof DeliveryModeValues[number];

export const DeliveryReasonValues = ['EVENT_ACKNOWLEDGED', 'EVENT_RESOLVED', 'CHANNEL_DISABLED', 'ADAPTER_DISABLED', 'CHANNEL_CHANGED', 'SECRET_UNAVAILABLE', 'TEMPLATE_INVALID', 'CHANNEL_NOT_CONFIGURED', 'OUTBOUND_BLOCKED', 'CONNECTION_FAILED', 'AUTHENTICATION_FAILED', 'RECIPIENT_REJECTED', 'RATE_LIMITED', 'REMOTE_REJECTED', 'REMOTE_UNAVAILABLE', 'UNKNOWN_RESULT', 'EVENT_SUPPRESSED'] as const;
export type DeliveryReason = typeof DeliveryReasonValues[number];

export const DigestStateValues = ['WAITING', 'ATTENTION', 'BUILDING', 'READY', 'EMPTY', 'SKIPPED'] as const;
export type DigestState = typeof DigestStateValues[number];

export const DigestPeriodValues = ['CALENDAR', 'LAST_24_HOURS'] as const;
export type DigestPeriod = typeof DigestPeriodValues[number];

export const DigestSelectionValues = ['FILTER', 'RULE'] as const;
export type DigestSelection = typeof DigestSelectionValues[number];

export const HealthStatusValues = ['HEALTHY', 'DEGRADED', 'UNAVAILABLE', 'UNKNOWN'] as const;
export type HealthStatus = typeof HealthStatusValues[number];

export const AttemptStatusValues = ['PROCESSING', 'SENT', 'FAILED', 'UNKNOWN'] as const;
export type AttemptStatus = typeof AttemptStatusValues[number];

export const WorkStateValues = ['PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED'] as const;
export type WorkState = typeof WorkStateValues[number];

export const ComponentCodeValues = ['DELIVERY', 'SMTP', 'INGESTION', 'DATABASE', 'BROKER', 'STORAGE', 'DISPATCHER', 'SCHEDULER', 'WORKER'] as const;
export type ComponentCode = typeof ComponentCodeValues[number];

export const HealthReasonValues = ['OK', 'UNREACHABLE', 'STALE', 'NOT_OBSERVED', 'LOW_SPACE'] as const;
export type HealthReason = typeof HealthReasonValues[number];

export const UserRoleValues = ['ADMINISTRATOR', 'OPERATOR', 'VIEWER'] as const;
export type UserRole = typeof UserRoleValues[number];

export const ErrorCodeValues = ['INGEST_KEY_LIMIT', 'RAW_MESSAGE_EXPIRED', 'CURSOR_INVALID', 'QUERY_TOO_BROAD', 'DIGEST_BACKLOG', 'DIGEST_STATE_CONFLICT', 'EVENT_STATE_CONFLICT', 'NOTIFICATION_STATE_CONFLICT', 'IDEMPOTENCY_CONFLICT', 'CHANNEL_SECRET_UNAVAILABLE', 'OUTBOUND_BLOCKED', 'CHANNEL_CONNECTION_FAILED', 'CHANNEL_UNAVAILABLE', 'ACTION_TARGET_UNAVAILABLE', 'CONFIGURATION_LIMIT', 'SOURCE_NAME_TAKEN', 'UNSUPPORTED_CONTENT_TYPE', 'INVALID_INPUT', 'INTERNAL_ERROR', 'VALIDATION_ERROR', 'VALIDATION_REQUIRED', 'RESOURCE_NOT_FOUND', 'METHOD_NOT_ALLOWED', 'ACCESS_DENIED', 'SESSION_EXPIRED', 'INVALID_CREDENTIALS', 'RATE_LIMITED', 'VERSION_CONFLICT', 'SERVICE_UNAVAILABLE', 'REQUEST_TOO_LARGE', 'MAIL_CONNECTION_FAILED', 'DELIVERY_FAILED', 'TEMPLATE_INVALID', 'CSRF_FAILED', 'USERNAME_TAKEN', 'LAST_ADMINISTRATOR', 'PASSWORD_POLICY', 'CURRENT_PASSWORD_INVALID'] as const;
export type ErrorCode = typeof ErrorCodeValues[number];

export const AuditActionValues = ['RETENTION_UPDATED', 'APPEARANCE_UPDATED', 'DIGEST_CREATED', 'DIGEST_UPDATED', 'DIGEST_PARTIAL', 'DIGEST_WAIT', 'EVENT_ACKNOWLEDGED', 'EVENT_RESOLVED', 'EVENT_SUPPRESSED', 'ESCALATION_POLICY_CREATED', 'ESCALATION_POLICY_UPDATED', 'NOTIFICATION_RETRIED', 'NOTIFICATION_CANCELLED', 'TEST_NOTIFICATION_CREATED', 'CHANNEL_CREATED', 'CHANNEL_UPDATED', 'CHANNEL_TESTED', 'OUTPUT_ADAPTER_UPDATED', 'TEMPLATE_CREATED', 'TEMPLATE_UPDATED', 'ROUTING_RULE_CREATED', 'ROUTING_RULE_UPDATED', 'SOURCE_CREATED', 'SOURCE_UPDATED', 'IDENTIFICATION_RULE_CREATED', 'IDENTIFICATION_RULE_UPDATED', 'DEDUP_POLICY_UPDATED', 'INGEST_KEY_CREATED', 'INGEST_KEY_REVOKED', 'LOGIN_SUCCEEDED', 'LOGIN_FAILED', 'LOGOUT', 'USER_CREATED', 'USER_UPDATED', 'USER_PASSWORD_CHANGED', 'ADMIN_BOOTSTRAPPED'] as const;
export type AuditAction = typeof AuditActionValues[number];

export const PermissionValues = ['VIEW_EVENTS', 'ACKNOWLEDGE_EVENTS', 'SUPPRESS_EVENTS', 'RESOLVE_EVENTS', 'RETRY_NOTIFICATIONS', 'CANCEL_NOTIFICATIONS', 'MANAGE_USERS', 'MANAGE_CONFIGURATION', 'VIEW_AUDIT', 'VIEW_SYSTEM_HEALTH', 'SEND_TEST_NOTIFICATION'] as const;
export type Permission = typeof PermissionValues[number];
