import { ApiError, requestJson } from './client';
import { bool, integer, page, record, string } from './configuration';
import { kinds, parsePreview, type Kind, type Preview } from './channels';
import { NotificationStatusValues, AttemptStatusValues, type NotificationStatus, type AttemptStatus } from './generated';
export interface Notification { id: string; event_id: string | null; channel_id: string; channel_name: string; channel_version: number; kind: Kind; subject: string; status: NotificationStatus; mode: string; created_at: string; due_at: string; finished_at: string | null; generation: number; attempt_count: number; max_attempts: number; failure_code: string | null; uncertain: boolean; version: number; is_test: boolean; dead_lettered: boolean }
export interface Detail extends Notification { prepared: Preview | null; retry_delays: number[] }
export interface Attempt { id: string; generation: number; attempt_number: number; started_at: string; finished_at: string | null; status: AttemptStatus; failure_code: string | null }
export interface Operation { operation_key: string; version: number }
export interface TestOperation { operation_key: string; channel_version: number; event: { subject: string; body: string } }
function bad() { return new ApiError({ key: 'errors.internalWithoutId' }); }
function id(v: unknown) { const s = string(v, 36); if (!/^[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12}$/.test(s)) throw bad(); return s; }
function date(v: unknown) { const s = string(v, 40); if (!Number.isFinite(Date.parse(s))) throw bad(); return s; }
export function parseNotification(value: unknown): Notification { const v = record(value); if (!NotificationStatusValues.includes(v.status as NotificationStatus) || !kinds.includes(v.kind as Kind)) throw bad(); return { id: id(v.id), event_id: v.event_id === null ? null : id(v.event_id), channel_id: id(v.channel_id), channel_name: string(v.channel_name, 120), channel_version: integer(v.channel_version), kind: v.kind as Kind, subject: string(v.subject, 1000), status: v.status as NotificationStatus, mode: string(v.mode, 16), created_at: date(v.created_at), due_at: date(v.due_at), finished_at: v.finished_at === null ? null : date(v.finished_at), generation: integer(v.generation), attempt_count: integer(v.attempt_count), max_attempts: integer(v.max_attempts), failure_code: v.failure_code === null ? null : string(v.failure_code, 40), uncertain: bool(v.uncertain), version: integer(v.version), is_test: bool(v.is_test), dead_lettered: bool(v.dead_lettered) }; }
export function parseAttempt(value: unknown): Attempt { const v = record(value); if (!AttemptStatusValues.includes(v.status as AttemptStatus)) throw bad(); return { id: id(v.id), generation: integer(v.generation), attempt_number: integer(v.attempt_number), started_at: date(v.started_at), finished_at: v.finished_at === null ? null : date(v.finished_at), status: v.status as AttemptStatus, failure_code: v.failure_code === null ? null : string(v.failure_code, 40) }; }
export function parseDetail(value: unknown): Detail { const v = record(value); if (!Array.isArray(v.retry_delays) || v.retry_delays.length > 8) throw bad(); return { ...parseNotification(value), prepared: v.prepared === null ? null : parsePreview(v.prepared), retry_delays: v.retry_delays.map(integer) }; }
export async function getNotifications(offset: number, filters: { status?: string; dead_lettered?: boolean; event_id?: string; channel_id?: string }, signal?: AbortSignal) { const params = new URLSearchParams({ offset: String(offset), limit: '25' }); for (const [k, v] of Object.entries(filters)) if (v) params.set(k, String(v)); return page(await requestJson('/api/v1/notifications?' + params, { signal }), parseNotification); }
export async function getNotification(identifier: string, signal?: AbortSignal) { return parseDetail(await requestJson(`/api/v1/notifications/${encodeURIComponent(identifier)}`, { signal })); }
export async function getAttempts(identifier: string, offset: number, signal?: AbortSignal) { return page(await requestJson(`/api/v1/notifications/${encodeURIComponent(identifier)}/attempts?offset=${offset}`, { signal }), parseAttempt); }
export async function mutateNotification(identifier: string, action: 'retry' | 'cancel', body: Operation, csrf: string) { return parseNotification(await requestJson(`/api/v1/notifications/${identifier}/${action}`, { method: 'POST', csrf, body })); }
export async function testNotification(identifier: string, body: TestOperation, csrf: string) { return parseNotification(await requestJson(`/api/v1/channels/${identifier}/test-notification`, { method: 'POST', csrf, body })); }
