from enum import StrEnum


class EventStatus(StrEnum):
    NEW = "NEW"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    SUPPRESSED = "SUPPRESSED"


class NotificationStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SENT = "SENT"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    CANCELLED = "CANCELLED"


class Severity(StrEnum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class DeliveryMode(StrEnum):
    IMMEDIATE = "IMMEDIATE"
    DELAYED = "DELAYED"
    SCHEDULED = "SCHEDULED"
    DIGEST = "DIGEST"


class HealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    UNKNOWN = "UNKNOWN"


class AttemptStatus(StrEnum):
    PROCESSING = "PROCESSING"
    SENT = "SENT"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class UserRole(StrEnum):
    ADMINISTRATOR = "ADMINISTRATOR"
    OPERATOR = "OPERATOR"
    VIEWER = "VIEWER"


class WorkState(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ComponentCode(StrEnum):
    DELIVERY = "DELIVERY"
    SMTP = "SMTP"
    INGESTION = "INGESTION"
    DATABASE = "DATABASE"
    BROKER = "BROKER"
    STORAGE = "STORAGE"
    DISPATCHER = "DISPATCHER"
    SCHEDULER = "SCHEDULER"
    WORKER = "WORKER"


class HealthReason(StrEnum):
    OK = "OK"
    UNREACHABLE = "UNREACHABLE"
    STALE = "STALE"
    NOT_OBSERVED = "NOT_OBSERVED"
    LOW_SPACE = "LOW_SPACE"


class DeliveryReason(StrEnum):
    EVENT_ACKNOWLEDGED = "EVENT_ACKNOWLEDGED"
    EVENT_RESOLVED = "EVENT_RESOLVED"
    CHANNEL_DISABLED = "CHANNEL_DISABLED"
    ADAPTER_DISABLED = "ADAPTER_DISABLED"
    CHANNEL_CHANGED = "CHANNEL_CHANGED"
    SECRET_UNAVAILABLE = "SECRET_UNAVAILABLE"
    TEMPLATE_INVALID = "TEMPLATE_INVALID"
    CHANNEL_NOT_CONFIGURED = "CHANNEL_NOT_CONFIGURED"
    OUTBOUND_BLOCKED = "OUTBOUND_BLOCKED"
    CONNECTION_FAILED = "CONNECTION_FAILED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    RECIPIENT_REJECTED = "RECIPIENT_REJECTED"
    RATE_LIMITED = "RATE_LIMITED"
    REMOTE_REJECTED = "REMOTE_REJECTED"
    REMOTE_UNAVAILABLE = "REMOTE_UNAVAILABLE"
    UNKNOWN_RESULT = "UNKNOWN_RESULT"
    EVENT_SUPPRESSED = "EVENT_SUPPRESSED"


class EscalationState(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    STOPPED = "STOPPED"


class EscalationStepState(StrEnum):
    WAITING = "WAITING"
    QUEUED = "QUEUED"
    CANCELLED = "CANCELLED"


class DigestState(StrEnum):
    WAITING = "WAITING"
    ATTENTION = "ATTENTION"
    BUILDING = "BUILDING"
    READY = "READY"
    EMPTY = "EMPTY"
    SKIPPED = "SKIPPED"


class DigestPeriod(StrEnum):
    CALENDAR = "CALENDAR"
    LAST_24_HOURS = "LAST_24_HOURS"


class DigestSelection(StrEnum):
    FILTER = "FILTER"
    RULE = "RULE"
