"""Generate enum contracts without starting the app or connecting to the database."""

# Local application imports require the repository path above site-packages.
# ruff: noqa: E402

import argparse
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root / "backend"))

from app.api.errors import ErrorCode
from app.domain.enums import (
    AttemptStatus,
    ComponentCode,
    DeliveryMode,
    DeliveryReason,
    DigestPeriod,
    DigestSelection,
    DigestState,
    EscalationState,
    EscalationStepState,
    EventStatus,
    HealthReason,
    HealthStatus,
    NotificationStatus,
    Severity,
    UserRole,
    WorkState,
)
from app.domain.rules.routing import ActionOutcome, RuleAction
from app.security.audit import AuditAction
from app.security.permissions import Permission

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
lines = ["// Generated by scripts/generate-api-types.py. Do not edit manually.", ""]
for enum in [
    RuleAction,
    ActionOutcome,
    EventStatus,
    EscalationState,
    EscalationStepState,
    NotificationStatus,
    Severity,
    DeliveryMode,
    DeliveryReason,
    DigestState,
    DigestPeriod,
    DigestSelection,
    HealthStatus,
    AttemptStatus,
    WorkState,
    ComponentCode,
    HealthReason,
    UserRole,
    ErrorCode,
    AuditAction,
    Permission,
]:
    name = enum.__name__
    values = ", ".join(f"'{entry.value}'" for entry in enum)
    lines.extend(
        [
            f"export const {name}Values = [{values}] as const;",
            f"export type {name} = typeof {name}Values[number];",
            "",
        ]
    )
content = "\n".join(lines)
target = root / "frontend/src/api/generated.ts"
if args.check:
    if not target.exists() or target.read_text() != content:
        raise SystemExit("API_TYPES_OUT_OF_DATE")
else:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
