import { useEffect, useState, type FormEvent } from 'react';
import { getAdapters, getTemplates, getTemplateVersions, saveTemplate, previewTemplate, kinds, kindKeys, type Adapter, type Template, type TemplateVersion, type Preview } from '../../api/channels';
import { safeFailure, type SafeError } from '../../api/client';
import { useI18n, type TranslationKey } from '../../i18n';
import { Field, ErrorNotice, Pagination } from '../../components/Forms';
import { useAuth } from '../auth/AuthContext';
const variables = { subject: 'events.subject', body: 'templates.eventBody', sender: 'sources.sender', source: 'templates.source', severity: 'events.severityLabel', category: 'config.category', event_type: 'config.eventType' } satisfies Record<string, TranslationKey>;
function History({ template, close }: { template: Template; close: () => void }) {
  const { t, formatDate, formatNumber } = useI18n(); const [rows, setRows] = useState<TemplateVersion[]>(), [error, setError] = useState<SafeError>(), [offset, setOffset] = useState(0), [total, setTotal] = useState(0);
  useEffect(() => { const c = new AbortController(); getTemplateVersions(template.id, offset, c.signal).then((r) => { if (!c.signal.aborted) { setRows(r.items); setTotal(r.total); } }).catch((e) => { if (!c.signal.aborted) setError(safeFailure(e)); }); return () => c.abort(); }, [template.id, offset]);
  return <section className="card"><div className="section-heading"><h2>{t('templates.historyNamed', { name: template.name })}</h2><button className="secondary" onClick={close}>{t('common.close')}</button></div><ErrorNotice error={error} />{rows?.map((r) => <details key={r.version}><summary>{t('config.versionSummary', { version: formatNumber(r.version), author: r.author, date: formatDate(r.created_at) })}</summary><h3>{t('templates.subject')}</h3><pre>{r.snapshot.subject}</pre><h3>{t('templates.body')}</h3><pre>{r.snapshot.body}</pre>{r.snapshot.html && <><h3>{t('templates.html')}</h3><pre>{r.snapshot.html}</pre></>}</details>)}<Pagination offset={offset} total={total} onChange={setOffset} /></section>;
}
export function TemplatesPage() {
  const { t } = useI18n(); const auth = useAuth();
  const [adapters, setAdapters] = useState<Adapter[]>([]);
  const [rows, setRows] = useState<Template[]>(), [draft, setDraft] = useState<Template>(), [history, setHistory] = useState<Template>(), [preview, setPreview] = useState<Preview>(), [sample, setSample] = useState<Record<string, string>>({});
  const [error, setError] = useState<SafeError>(), [busy, setBusy] = useState(false), [saved, setSaved] = useState(false), [revision, setRevision] = useState(0);
  useEffect(() => { const c = new AbortController(); Promise.all([getTemplates(c.signal), getAdapters(c.signal)]).then(([r, a]) => { if (!c.signal.aborted) { setRows(r.items); setAdapters(a.items); } }).catch((e) => { if (!c.signal.aborted) setError(safeFailure(e)); }); return () => c.abort(); }, [revision]);
  function change(v: Template) { setDraft(v); setPreview(undefined); setSaved(false); }
  async function run(save: boolean, event?: FormEvent) { event?.preventDefault(); if (!draft || !auth.identity || busy) return; setError(undefined); setPreview(undefined); if (!draft.name.trim() || !draft.body.trim()) { setError({ key: 'templates.required' }); return; } setBusy(true); try { if (save) { await saveTemplate(draft, auth.identity.csrf_token); setDraft(undefined); setSaved(true); setRevision((v) => v + 1); } else setPreview(await previewTemplate(draft, sample, auth.identity.csrf_token)); } catch (e) { setError(safeFailure(e)); } finally { setBusy(false); } }
  return <>
    <div className="section-heading"><h1>{t('navigation.templates')}</h1><button disabled={busy || !adapters.some((a) => a.enabled && a.visible)} onClick={() => { change({ id: '', name: '', kind: adapters.find((a) => a.enabled && a.visible)!.kind, version: 1, subject: '{{ event.subject }}', body: '{{ event.body }}', html: '' }); setHistory(undefined); setError(undefined); }}>{t('templates.create')}</button></div>
    <p className="muted">{t('templates.hint')}</p><ErrorNotice error={error} />{saved && <p className="notice" role="status">{t('templates.saved')}</p>}
    {draft && <form noValidate className="card" onSubmit={(e) => void run(true, e)}><h2>{t(draft.id ? 'templates.edit' : 'templates.create')}</h2><fieldset disabled={busy}>
      <Field id="template-name" labelKey="config.name"><input id="template-name" maxLength={120} value={draft.name} onChange={(e) => change({ ...draft, name: e.target.value })} /></Field>
      <Field id="template-kind" labelKey="channels.kind"><select id="template-kind" disabled={Boolean(draft.id)} value={draft.kind} onChange={(e) => change({ ...draft, kind: e.target.value as Template['kind'], html: '' })}>{kinds.filter((k) => k === draft.kind && Boolean(draft.id) || adapters.some((a) => a.kind === k && a.visible && a.enabled)).map((k) => <option key={k} value={k}>{t(kindKeys[k])}</option>)}</select></Field>
      <Field id="template-subject" labelKey="templates.subject" hint="templates.subjectHint"><input id="template-subject" maxLength={2000} value={draft.subject} onChange={(e) => change({ ...draft, subject: e.target.value })} /></Field>
      <Field id="template-body" labelKey="templates.body" hint="templates.variablesHint"><textarea id="template-body" rows={6} maxLength={16384} value={draft.body} onChange={(e) => change({ ...draft, body: e.target.value })} /></Field>
      <div className="form-actions">{Object.entries(variables).map(([key, label]) => <button type="button" className="secondary compact" key={key} onClick={() => change({ ...draft, body: draft.body + `{{ event.${key} }}` })}>{t('templates.insert', { name: t(label) })}</button>)}</div>
      {draft.kind === 'SMTP' && <Field id="template-html" labelKey="templates.html" hint="templates.htmlHint"><textarea id="template-html" rows={4} maxLength={16384} value={draft.html} onChange={(e) => change({ ...draft, html: e.target.value })} /></Field>}
      {draft.kind === 'WEBHOOK' && <p className="field-hint">{t('templates.jsonHint')}</p>}
      <details><summary>{t('templates.sample')}</summary>{Object.entries(variables).map(([key, label]) => <Field key={key} id={`sample-${key}`} labelKey={label}><textarea id={`sample-${key}`} rows={2} maxLength={key === 'body' ? 4096 : key === 'subject' ? 1000 : key === 'sender' ? 320 : 120} value={sample[key] ?? ''} onChange={(e) => { setSample({ ...sample, [key]: e.target.value }); setPreview(undefined); }} /></Field>)}</details>
      <div className="form-actions"><button type="submit">{t('common.save')}</button><button type="button" className="secondary" onClick={() => void run(false)}>{t('templates.preview')}</button><button type="button" className="secondary" onClick={() => { setDraft(undefined); setPreview(undefined); setError(undefined); }}>{t('common.cancel')}</button></div>
    </fieldset></form>}
    {preview && <section className="card" aria-label={t('templates.preview')}><h2>{t('templates.preview')}</h2><p>{t('templates.previewHint')}</p><h3>{t('templates.subject')}</h3><p>{preview.subject}</p><h3>{t('templates.body')}</h3><pre>{preview.body}</pre>{preview.html && <><h3>{t('templates.htmlPreview')}</h3><iframe title={t('templates.htmlPreview')} sandbox="" referrerPolicy="no-referrer" srcDoc={`<!doctype html><html lang="ru"><head><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'none'; form-action 'none'; base-uri 'none'"></head><body>${preview.html}</body></html>`} /></>}{preview.payload && <><h3>{t('templates.payload')}</h3><pre>{preview.payload}</pre></>}</section>}
    {history && <History key={history.id} template={history} close={() => setHistory(undefined)} />}
    {!rows && !error && <p role="status">{t('common.loading')}</p>}
    {rows && <div className="card table-scroll" tabIndex={0} role="region" aria-label={t('common.scrollTable')}>{rows.length === 0 ? <p>{t('templates.empty')}</p> : <table><thead><tr><th>{t('config.name')}</th><th>{t('channels.kind')}</th><th>{t('users.actions')}</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.name}</td><td>{t(kindKeys[r.kind])}</td><td><div className="form-actions"><button disabled={busy} className="secondary compact" aria-label={t('config.editNamed', { name: r.name })} onClick={() => { change(r); setError(undefined); setHistory(undefined); }}>{t('common.edit')}</button><button className="secondary compact" aria-label={t('templates.historyNamed', { name: r.name })} onClick={() => { setHistory(r); setDraft(undefined); setPreview(undefined); }}>{t('config.history')}</button></div></td></tr>)}</tbody></table>}</div>}
  </>;
}
