"""ingestion"""

import sqlalchemy as sa
from alembic import op

revision = "0004"
down_revision = "0003_background"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adapter_installations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.CheckConstraint("kind IN ('SMTP','REST')", name="ck_input_kind"),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "kind", name="uq_adapter_team_kind"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("input_adapter", sa.String(length=16), nullable=False),
        sa.Column("sender", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "severity IS NULL OR severity IN ('DEBUG','INFO','WARNING','ERROR','CRITICAL')",
            name="ck_event_severity",
        ),
        sa.CheckConstraint(
            "status IN ('NEW','ACKNOWLEDGED','RESOLVED','SUPPRESSED')", name="ck_event_status"
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_event_team_received", "events", ["team_id", "received_at", "id"], unique=False
    )
    op.create_table(
        "ingest_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_start", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "raw_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("adapter_id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_hash", sa.String(length=64), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("blob_id", sa.Uuid(), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("envelope_sender", sa.String(length=320), nullable=False),
        sa.Column("recipients", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("headers", sa.JSON(), nullable=False),
        sa.CheckConstraint("state IN ('PENDING','NORMALIZED','LIMITED')", name="ck_raw_state"),
        sa.ForeignKeyConstraint(
            ["adapter_id"],
            ["adapter_installations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["blobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["ingest_credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blob_id"),
        sa.UniqueConstraint("credential_id", "idempotency_hash", name="uq_ingest_idempotency"),
    )
    op.create_index(
        "ix_raw_team_received", "raw_messages", ["team_id", "received_at"], unique=False
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_message_id", sa.Uuid(), nullable=False),
        sa.Column("blob_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["blobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["raw_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blob_id"),
    )
    op.create_index(
        op.f("ix_attachments_raw_message_id"), "attachments", ["raw_message_id"], unique=False
    )
    op.create_table(
        "event_occurrences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("raw_message_id", sa.Uuid(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["raw_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("raw_message_id"),
    )
    op.create_index(
        "ix_occurrence_event_received",
        "event_occurrences",
        ["event_id", "received_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_occurrence_event_received", table_name="event_occurrences")
    op.drop_table("event_occurrences")
    op.drop_index(op.f("ix_attachments_raw_message_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index("ix_raw_team_received", table_name="raw_messages")
    op.drop_table("raw_messages")
    op.drop_table("ingest_credentials")
    op.drop_index("ix_event_team_received", table_name="events")
    op.drop_table("events")
    op.drop_table("adapter_installations")
    # ### end Alembic commands ###
