"""sources and deduplication"""

import sqlalchemy as sa
from alembic import op

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dedup_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=36), nullable=False),
        sa.Column("inherit", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("window_seconds", sa.Integer(), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("window_seconds BETWEEN 1 AND 86400", name="ck_dedup_window"),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "scope", name="uq_dedup_scope"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "name", name="uq_source_name"),
    )
    op.create_table(
        "dedup_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("canonical", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["dedup_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id", "policy_id", "policy_version", "fingerprint", name="uq_dedup_fingerprint"
        ),
    )
    op.create_table(
        "identification_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("assignments", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_identification_priority",
        "identification_rules",
        ["team_id", "priority", "id"],
        unique=False,
    )
    op.create_table(
        "rule_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["identification_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "version", name="uq_rule_version"),
    )
    with op.batch_alter_table("events") as batch:
        batch.add_column(sa.Column("source_id", sa.Uuid(), nullable=True))
        batch.add_column(sa.Column("dedup_key_id", sa.Uuid(), nullable=True))
        batch.add_column(sa.Column("category", sa.String(120), nullable=False, server_default=""))
        batch.add_column(sa.Column("event_type", sa.String(120), nullable=False, server_default=""))
        batch.add_column(sa.Column("tags", sa.JSON(), nullable=False, server_default="[]"))
        batch.create_foreign_key("fk_event_source", "sources", ["source_id"], ["id"])
        batch.create_foreign_key("fk_event_dedup", "dedup_keys", ["dedup_key_id"], ["id"])
        batch.create_index("ix_events_dedup_key_id", ["dedup_key_id"])
    with op.batch_alter_table("event_occurrences") as batch:
        batch.add_column(
            sa.Column("normalized_snapshot", sa.JSON(), nullable=False, server_default="{}")
        )
        batch.add_column(sa.Column("rule_version_id", sa.Uuid(), nullable=True))
        batch.create_foreign_key(
            "fk_occurrence_rule_version", "rule_versions", ["rule_version_id"], ["id"]
        )
    connection = op.get_bind()
    metadata = sa.MetaData()
    events = sa.Table("events", metadata, autoload_with=connection)
    occurrences = sa.Table("event_occurrences", metadata, autoload_with=connection)
    rows = connection.execute(
        sa.select(
            occurrences.c.id, events.c.sender, events.c.subject, events.c.body, events.c.severity
        )
        .join(events, events.c.id == occurrences.c.event_id)
        .execution_options(yield_per=100)
    )
    for row in rows:
        connection.execute(
            occurrences.update()
            .where(occurrences.c.id == row.id)
            .values(
                normalized_snapshot=dict(
                    sender=row.sender,
                    subject=row.subject,
                    body=row.body,
                    severity=row.severity,
                    category="",
                    event_type="",
                    tags=[],
                )
            )
        )


def downgrade():
    with op.batch_alter_table("event_occurrences") as batch:
        batch.drop_constraint("fk_occurrence_rule_version", type_="foreignkey")
        batch.drop_column("rule_version_id")
        batch.drop_column("normalized_snapshot")
    with op.batch_alter_table("events") as batch:
        batch.drop_constraint("fk_event_source", type_="foreignkey")
        batch.drop_constraint("fk_event_dedup", type_="foreignkey")
        batch.drop_index("ix_events_dedup_key_id")
        for column in ("source_id", "dedup_key_id", "category", "event_type", "tags"):
            batch.drop_column(column)
    op.drop_table("rule_versions")
    op.drop_index("ix_identification_priority", table_name="identification_rules")
    op.drop_table("identification_rules")
    op.drop_table("dedup_keys")
    op.drop_table("sources")
    op.drop_table("dedup_policies")
