import { useEffect, useState, type FormEvent } from 'react';
import { getDigests, newDigest, saveDigest, type Digest } from '../../api/digests';
import { getChannels, getTemplates, type Channel, type Template } from '../../api/channels';
import { getSources, type Source } from '../../api/configuration';
import { safeFailure, type SafeError } from '../../api/client';
import { useAuth } from '../auth/AuthContext';
import { useI18n } from '../../i18n';
import { ErrorNotice } from '../../components/Forms';
import { DigestFields } from './DigestFields';
import { DigestHistory, DigestPreview, DigestVersions } from './DigestHistory';
export function DigestsPage() {
  const { t, formatDate, formatTimeZone } = useI18n(); const auth = useAuth(); const admin = auth.identity?.user.role === 'ADMINISTRATOR';
  const [rows, setRows] = useState<Digest[]>(), [channels, setChannels] = useState<Channel[]>([]), [templates, setTemplates] = useState<Template[]>([]), [sources, setSources] = useState<Source[]>([]), [draft, setDraft] = useState<Digest>(), [selected, setSelected] = useState<{ digest: Digest; tab: 'history' | 'preview' | 'versions' }>();
  const [revision, setRevision] = useState(0), [error, setError] = useState<SafeError>(), [busy, setBusy] = useState(false), [saved, setSaved] = useState(false);
  useEffect(() => { const c = new AbortController(); setError(undefined); getDigests(c.signal).then((v) => { if (!c.signal.aborted) setRows(v.items); }).catch((e) => { if (!c.signal.aborted) setError(safeFailure(e)); }); if (admin) Promise.all([getChannels(c.signal), getTemplates(c.signal), getSources(c.signal)]).then(([ch, tm, s]) => { if (!c.signal.aborted) { setChannels(ch.items); setTemplates(tm.items); setSources(s.items); } }).catch((e) => { if (!c.signal.aborted) setError(safeFailure(e)); }); return () => c.abort(); }, [revision, admin]);
  async function submit(e: FormEvent) { e.preventDefault(); if (!draft || !auth.identity || busy) return; if (!draft.name.trim() || !draft.channel_id || !draft.template_id || !Number.isInteger(draft.minute_of_day) || draft.minute_of_day < 0 || draft.minute_of_day > 1439 || !Number.isInteger(draft.wait_seconds / 60) || draft.wait_seconds < 60 || draft.wait_seconds > 604800) { setError({ key: 'digests.invalid' }); return; } setBusy(true); setError(undefined); try { await saveDigest(draft, auth.identity.csrf_token); setDraft(undefined); setSaved(true); setRevision((v) => v + 1); } catch (e) { setError(safeFailure(e)); } finally { setBusy(false); } }
  return <><div className="section-heading"><h1>{t('digests.title')}</h1><div className="form-actions"><button className="secondary" onClick={() => setRevision((v) => v + 1)}>{t('common.refresh')}</button>{admin && <button onClick={() => { setDraft(newDigest()); setSelected(undefined); setSaved(false); setError(undefined); }}>{t('digests.create')}</button>}</div></div><p className="field-hint">{t('health.timeZone', { zone: formatTimeZone(new Date()) })}</p><ErrorNotice error={error} />{saved && <p role="status">{t('digests.saved')}</p>}{!rows && !error && <p role="status">{t('common.loading')}</p>}
    {draft && <form className="card" noValidate onSubmit={(e) => void submit(e)}><h2>{t(draft.id ? 'digests.edit' : 'digests.create')}</h2><DigestFields value={draft} change={setDraft} channels={channels} templates={templates} sources={sources} readOnly={busy} /><div className="form-actions"><button disabled={busy}>{t('common.save')}</button><button className="secondary" type="button" disabled={busy} onClick={() => setDraft(undefined)}>{t('common.close')}</button></div></form>}
    {selected && <><div className="section-heading"><h2>{selected.digest.name}</h2><button className="secondary" onClick={() => setSelected(undefined)}>{t('common.close')}</button></div>{selected.tab === 'history' ? <DigestHistory key={selected.digest.id} digest={selected.digest} /> : selected.tab === 'preview' ? <DigestPreview key={selected.digest.id} digest={selected.digest} /> : <DigestVersions key={selected.digest.id} digest={selected.digest} />}</>}
    {rows && <section className="card table-scroll" tabIndex={0} role="region" aria-label={t('common.scrollTable')}>{rows.length === 0 ? <p>{t('digests.empty')}</p> : <table className="digest-table"><thead><tr><th>{t('config.name')}</th><th>{t('users.status')}</th><th>{t('digests.next')}</th><th>{t('users.actions')}</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.name}</td><td>{t(r.enabled ? 'config.enabled' : 'config.disabled')}</td><td>{r.next_end && formatDate(r.next_end)}</td><td><div className="form-actions">{admin && <button className="secondary" onClick={() => { setDraft(r); setSelected(undefined); setSaved(false); }}>{t('common.edit')}</button>}{(['history', 'preview', 'versions'] as const).map((tab) => <button key={tab} className="secondary" onClick={() => { setDraft(undefined); setSelected({ digest: r, tab }); }}>{t(tab === 'history' ? 'digests.history' : tab === 'preview' ? 'digests.preview' : 'config.history')}</button>)}</div></td></tr>)}</tbody></table>}</section>}
  </>;
}
