import { useEffect, useState } from 'react';
import { decide, getItems, getPreview, getRuns, getVersions, type Digest, type Item, type Run, type Summary } from '../../api/digests';
import type { Operation } from '../../api/notifications';
import { safeFailure, type SafeError } from '../../api/client';
import { ErrorNotice, Pagination } from '../../components/Forms';
import { useI18n } from '../../i18n';
import { digestStates, digestPeriods, notificationStatuses, severities } from '../../i18n/mappings';
import { useAuth } from '../auth/AuthContext';
export function ItemList({ items }: { items: Item[] }) { const { t, formatDate } = useI18n(); return items.length ? <ul>{items.map((v, i) => <li key={i}><a href={`#events/${v.event_id}`}>{v.subject || t('events.noSubject')}</a><p>{formatDate(v.received_at)}</p></li>)}</ul> : <p>{t('digests.noItems')}</p>; }
function Items({ run, late, close }: { run: Run; late: boolean; close: () => void }) {
  const { t } = useI18n(); const [data, setData] = useState<Awaited<ReturnType<typeof getItems>>>(), [offset, setOffset] = useState(0), [error, setError] = useState<SafeError>();
  useEffect(() => { const c = new AbortController(); setData(undefined); setError(undefined); getItems(run.id, late, offset, c.signal).then((v) => { if (!c.signal.aborted) setData(v); }).catch((e) => { if (!c.signal.aborted) setError(safeFailure(e)); }); return () => c.abort(); }, [run.id, late, offset]);
  return <section className="policy-fields"><div className="section-heading"><h3>{t(late ? 'digests.late' : 'digests.items')}</h3><button className="secondary" onClick={close}>{t('common.close')}</button></div><ErrorNotice error={error} />{data ? <><ItemList items={data.items} /><Pagination offset={offset} total={data.total} onChange={setOffset} /></> : !error && <p role="status">{t('common.loading')}</p>}</section>;
}
function Totals({ value }: { value: Summary }) { const { t, formatNumber, formatDate } = useI18n(); return <><p>{t('digests.counts', { occurrences: formatNumber(value.occurrences), events: formatNumber(value.events) })}</p>{value.first && value.last && <p>{t('digests.range', { first: formatDate(value.first), last: formatDate(value.last) })}</p>}<p className="field-hint">{t('digests.totalsHint')}</p><details><summary>{t('digests.sources')}</summary><ul>{value.sources.map((v) => <li key={v.label}>{t('digests.group', { label: v.label, count: formatNumber(v.count) })}</li>)}</ul></details><details><summary>{t('digests.severities')}</summary><ul>{value.severities.map((v) => <li key={v.label}>{t('digests.group', { label: t(v.label ? severities[v.label] : 'events.severity.unset'), count: formatNumber(v.count) })}</li>)}</ul></details><details><summary>{t('digests.frequent')}</summary><ul>{value.frequent.map((v) => <li key={v.event_id}><a href={`#events/${v.event_id}`}>{t('digests.group', { label: v.subject || t('events.noSubject'), count: formatNumber(v.count) })}</a></li>)}</ul></details></>; }
export function DigestHistory({ digest }: { digest: Digest }) {
  const { t, formatDate, formatNumber } = useI18n(); const auth = useAuth(); const admin = auth.identity?.user.role === 'ADMINISTRATOR';
  const [data, setData] = useState<Awaited<ReturnType<typeof getRuns>>>(), [offset, setOffset] = useState(0), [revision, setRevision] = useState(0), [error, setError] = useState<SafeError>(), [busy, setBusy] = useState(false), [saved, setSaved] = useState(false);
  const [operation, setOperation] = useState<{ run: Run; action: 'wait' | 'partial'; body: Operation }>(), [items, setItems] = useState<{ run: Run; late: boolean }>();
  useEffect(() => { const c = new AbortController(); let timer: ReturnType<typeof setTimeout> | undefined; async function load() { try { const v = await getRuns(digest.id, offset, c.signal); if (!c.signal.aborted) { setData(v); setError(undefined); if (v.items.some((r) => ['WAITING', 'ATTENTION', 'BUILDING'].includes(r.state) || (r.partial && r.pending_count > 0))) timer = setTimeout(() => void load(), 5000); } } catch (e) { if (!c.signal.aborted) setError(safeFailure(e)); } } void load(); return () => { c.abort(); clearTimeout(timer); }; }, [digest.id, offset, revision]);
  async function confirm() { if (!operation || !auth.identity || busy) return; setBusy(true); setError(undefined); try { await decide(operation.run.id, operation.action, operation.body, auth.identity.csrf_token); setOperation(undefined); setSaved(true); setRevision((v) => v + 1); } catch (e) { setError(safeFailure(e)); } finally { setBusy(false); } }
  return <section className="card"><div className="section-heading"><h2>{t('digests.history')}</h2><button className="secondary" onClick={() => setRevision((v) => v + 1)}>{t('common.refresh')}</button></div><ErrorNotice error={error} />{saved && <p role="status">{t('digests.decisionSaved')}</p>}{!data && !error && <p role="status">{t('common.loading')}</p>}{data?.items.length === 0 && <p>{t('digests.noRuns')}</p>}
    {operation && <div role="alertdialog" aria-labelledby="digest-confirm"><h3 id="digest-confirm">{t(operation.action === 'partial' ? 'digests.partialAction' : 'digests.waitAction')}</h3><p>{t(operation.action === 'partial' ? 'digests.partialConfirm' : 'digests.waitConfirm')}</p><div className="form-actions"><button disabled={busy} onClick={() => void confirm()}>{t(operation.action === 'partial' ? 'digests.partialAction' : 'digests.waitAction')}</button><button className="secondary" disabled={busy} onClick={() => setOperation(undefined)}>{t('common.close')}</button></div></div>}
    {data?.items.map((r) => <article className="rule-version" key={r.id}><h3>{t('digests.window', { start: formatDate(r.window_start), end: formatDate(r.window_end) })}</h3><p>{t(digestStates[r.state])}</p><p className="field-hint">{t('digests.version', { version: formatNumber(r.definition_version) })}</p>{r.partial && <p className="notice warning">{t('digests.partial')}</p>}{r.pending_count > 0 && <p>{t('digests.pending', { count: formatNumber(r.pending_count) })}</p>}{r.partial && <><p>{t('digests.missing', { count: formatNumber(r.missing_at_cutoff) })}</p><p>{t('digests.lateHint', { count: formatNumber(r.late_count) })}</p></>}{r.summary && <Totals value={r.summary} />}{r.notification_id && r.notification_status && <p><a href={`#notifications/${r.notification_id}`}>{t(notificationStatuses[r.notification_status])}</a></p>}<div className="form-actions"><button className="secondary" onClick={() => setItems({ run: r, late: false })}>{t('digests.items')}</button>{r.partial && <button className="secondary" onClick={() => setItems({ run: r, late: true })}>{t('digests.late')}</button>}{admin && r.state === 'ATTENTION' && (['wait', 'partial'] as const).map((action) => <button key={action} disabled={busy || Boolean(operation)} onClick={() => { setSaved(false); setOperation({ run: r, action, body: { version: r.version, operation_key: crypto.randomUUID() } }); }}>{t(action === 'partial' ? 'digests.partialAction' : 'digests.waitAction')}</button>)}</div>{items?.run.id === r.id && <Items key={`${r.id}-${items.late}`} {...items} close={() => setItems(undefined)} />}</article>)}{data && <Pagination offset={offset} total={data.total} onChange={setOffset} />}
  </section>;
}
export function DigestPreview({ digest }: { digest: Digest }) { const { t, formatDate, formatNumber } = useI18n(); const [data, setData] = useState<Awaited<ReturnType<typeof getPreview>>>(), [error, setError] = useState<SafeError>(); useEffect(() => { const c = new AbortController(); getPreview(digest.id, c.signal).then((v) => { if (!c.signal.aborted) setData(v); }).catch((e) => { if (!c.signal.aborted) setError(safeFailure(e)); }); return () => c.abort(); }, [digest.id]); return <section className="card"><h2>{t('digests.preview')}</h2><p className="field-hint">{t('digests.previewHint')}</p><ErrorNotice error={error} />{data ? <><p>{t('digests.window', { start: formatDate(data.window_start), end: formatDate(data.window_end) })}</p><p>{t('digests.counts', { occurrences: formatNumber(data.occurrences), events: formatNumber(data.events) })}</p><p>{t('digests.pending', { count: formatNumber(data.pending_count) })}</p><ItemList items={data.items} /></> : !error && <p role="status">{t('common.loading')}</p>}</section>; }
export function DigestVersions({ digest }: { digest: Digest }) { const { t, formatDate, formatNumber } = useI18n(); const [data, setData] = useState<Awaited<ReturnType<typeof getVersions>>>(), [error, setError] = useState<SafeError>(), [offset, setOffset] = useState(0); useEffect(() => { const c = new AbortController(); getVersions(digest.id, offset, c.signal).then((v) => { if (!c.signal.aborted) setData(v); }).catch((e) => { if (!c.signal.aborted) setError(safeFailure(e)); }); return () => c.abort(); }, [digest.id, offset]); return <section className="card"><h2>{t('config.history')}</h2><ErrorNotice error={error} />{data?.items.map((v) => <details key={v.version}><summary>{t('config.versionSummary', { version: formatNumber(v.version), author: v.author, date: formatDate(v.created_at) })}</summary><p>{v.snapshot.name}</p><p>{v.snapshot.description}</p><p>{t(v.snapshot.enabled ? 'config.enabled' : 'config.disabled')}</p><p>{t(digestPeriods[v.snapshot.period])}</p></details>)}{data && <Pagination offset={offset} total={data.total} onChange={setOffset} />}</section>; }
